# How often do you want to save output images during training.
image_save_iter: 10
# How often do you want to save trained models.
snapshot_save_iter: 1
# How often do you want to log the training stats.
logging_iter: 10
# Number of training epochs.
max_epoch: 500
# Number of epochs training single frame generator.
single_frame_epoch: 0
# How often to double the number of training frames in each clip.
num_epochs_temporal_step: 1

# Trainer options.
trainer:
    type: imaginaire.trainers.vid2vid
    amp_config:
        enabled: True
    model_average_config:
        enabled: True
        beta: 0.999
        start_iteration: 500
        num_batch_norm_estimation_iterations: 0
    num_frames_per_video: 30 

    gan_mode: hinge
    gan_relativistic: False
    perceptual_loss:
        mode: 'vgg19'
        layers: ['relu_1_1', 'relu_2_1', 'relu_3_1', 'relu_4_1', 'relu_5_1']
        weights: [0.03125, 0.0625, 0.125, 0.25, 1.0]
    loss_weight:
        gan: 1.0
        feature_matching: 10.0        
        temporal_gan: 0.00000001
        perceptual: 10.0
        flow: 10.0
    init:
        type: xavier
        gain: 0.02
    distributed_data_parallel_params:
        find_unused_parameters: True

# Optimization option.
gen_opt:
    type: adam
    lr: 0.0001
    adam_beta1: 0.
    adam_beta2: 0.999
    lr_policy:
        iteration_mode: False
        type: step
        step_size: 100
        gamma: 0.5
dis_opt:
    type: adam
    fused_opt: True
    lr: 0.0004
    adam_beta1: 0.
    adam_beta2: 0.999
    lr_policy:
        iteration_mode: False
        type: step
        step_size: 100
        gamma: 0.5


# Model options.
gen:  
    type: imaginaire.generators.vid2vid
    num_filters: 32
    max_num_filters: 1024
    num_downsamples: 5
    activation_norm_type: spatially_adaptive
    activation_norm_params:
        activation_norm_type: instance
        num_filters: 0
        kernel_size: 1
    weight_norm_type: spectral
    do_checkpoint: True
    flow:
        generate_raw_output: False
        num_filters: 32
        max_num_filters: 1024
        num_downsamples: 3
        num_res_blocks: 6
        activation_norm_type: instance
        weight_norm_type: spectral
        flow_output_multiplier: 20
        multi_spade_combine:
            num_layers: 3
            embed:
                arch: unet
                num_filters: 32
                num_downsamples: 5
                kernel_size: 3
                weight_norm_type: spectral
    embed:
        use_embed: True
        arch: encoderdecoder
        num_filters: 32
        num_downsamples: 5
        kernel_size: 3
        weight_norm_type: spectral
dis:
    type: imaginaire.discriminators.fs_vid2vid
    image:
        num_filters: 32
        max_num_filters: 512
        num_discriminators: 2
        num_layers: 4
        weight_norm_type: spectral
        activation_norm_type: instance
flow_network:
    type: imaginaire.third_party.flow_net.flow_net

########
# TRAIN
########

data:
    name: 'mesh'
    type: imaginaire.datasets.paired_videos
    num_frames_G: 3
    num_frames_D: 3    
    has_foreground: False
    num_workers: 8

    input_types:
        - images:
            ext: jpg
            num_channels: 3
            normalize: True 
        - mesh_images:
            ext: jpg
            num_channels: 3
            normalize: True

    full_data_ops: imaginaire.model_utils.label::concat_labels
    
    input_labels:
        - mesh_images
    input_image:
        - images

    train:        
        roots:
            - ./replace/with/train/data/root  
        batch_size: 8
        initial_sequence_length: 176
        max_sequence_length: 176    
        augmentations:
            resize_h_w: 256, 256
            horizontal_flip: False     

    val:        
        roots:
            - ./replace/with/val/data/root
        batch_size: 1     
        augmentations:           
            resize_h_w: 256, 256
            horizontal_flip: False   

########
# TEST
########

inference_args:    
    seq_index: 0

test_data:
    name: 'pose'
    type: imaginaire.datasets.paired_videos
    num_workers: 8
    has_foreground: True
    paired: True    
    input_types:
        - images:
            ext: jpg
            num_channels: 3
            normalize: True
        - mesh_images:
            ext: jpg
            num_channels: 3
            normalize: True

    full_data_ops: imaginaire.model_utils.label::concat_labels
    input_labels:
        - mesh_images
    input_image:
        - images

    test:
        is_lmdb: False
        roots:
            - ./replace/with/test/data/root
        batch_size: 1
        augmentations:
            resize_h_w: 256, 256
            horizontal_flip: False
